### ISSUE TITLE
`aggregate_spatial` with vector-cubes

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-python#101]
Issue for the implementation of `aggregate_spatial` using vector-cubes as output data type.

The current proposal is here: https://github.com/clausmichele/openeo_aggregate_spatial_vector_cubes

It's based on geopandas and shapely. It can get as input a dictionary (a geoJSON parsed from Python) or a geopandas.GeoDataframe.

The output can be written as a geoJSON or re-used internally as a geopandas object in other processes, like `fit_regr_random_forest`.

**Comment by LukeWeidenwalker** [comment]
Closed with https://github.com/Open-EO/openeo-processes-python/pull/140
