### ISSUE TITLE
Unpin xarray version

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-python#116]
@ValentinaHutter Is there a specific reason why xarray is pinned to 0.18.2? Unpinning this would make installation on dask-gateway much easier!

**Comment by soxofaan** [comment]
FYI: About pinned dependencies: [this blog post](https://caremad.io/posts/2013/07/setup-vs-requirement/)  was enlightening to me back in the time when I was struggling with the same question.
Short version:
- applications (software you deploy) should have their dependencies pinned down in `requirements.txt`  (or something equivalent)
- libraries (software you package to be reused/redistributed in other applications and environments, like openeo-processes-python)  should have abstract, liberally constrained dependencies in `setup.py`/`setup.cfg`. And with liberally constrained I mean something like `foo>=1.2.3`: we need at least version 1.2.3 of library foo and anything above that should work too

**Comment by LukeWeidenwalker** [comment]
Thanks, this is very helpful, that's a clear way to think about it - I think I will start linking to that article myself! ;)

I'll update `xarray>=0.18.2`, that should
