### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes-python#15]
In https://github.com/Open-EO/openeo-python-driver, we're planning to depend on openeo-processes-python and to do that properly we need a releases/version of this package.

Are there plans already to create a release on https://pypi.org/? I can help out with practicalities if you want

**Comment by lforesta** [comment]
@soxofaan it would be great if you could lead / provide support for this

**Comment by soxofaan** [comment]
hi @lforesta , sorry for late response, 

I managed to create a release on the test pypi.org setup: https://test.pypi.org/project/openeo-processes/  (note: this test setup is flushed regularly, so that page might disappear soon).

To do it properly, and because this project uses pyscaffold, we need a version tag on a recent commit. The latest and only git tag is `v0.0.1`, dating back to February, when the project was called eoFunctions. Can you create a new version tag (e.g. `v0.0.2`) on latest master and push it?  Or would it be possible to give me push rights on this repo?

**Comment by lforesta** [comment]
Thanks @soxofaan for the help creating a release!

I gave you push rights, feel free to tag a new version

**Comment by soxofaan** [comment]
great, thanks

I created a release for version 0.0.2 (3beb7cd): 
- on PyPI: https://pypi.org/project/openeo-processes/0.0.2/
- on github: https://github.com/Open-EO/openeo-processes-python/releases/tag/v0.0.2

**Comment by soxofaan** [comment]
I also created a release v0.0.3 from 58a547e

unfortunately I can not create release of latest master because there is failing test, see #17

**Comment by soxofaan** [comment]
closing this issue for now
