### ISSUE TITLE
Allow file format to be upper/lowercase in save_results 

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-processes-python#22]
According to the openEO API spec: "Format names are allowed to be case insensitive throughout the API."

**Comment by soxofaan** [comment]
This actually raises the question why it states "are allowed to be case insensitive".
Does this mean that a backend can choose to be case insensitive about format names?
Wouldn't it be better (for portability) to enforce that format names are case insensitive?
(same for `Service names` and `Billing plans` by the way)

cc @m-mohr

**Comment by m-mohr** [comment]
A back-end must accept formats case-insensitive to make it easier for users to use. We had a number of workshops where people had issues with that, e.g. the back-end exposed "GTiff" and people just typed "gtiff" in the client. This is purely for a better user-experience.

**Comment by m-mohr** [comment]
See PR #372

**Comment by clausmichele** [comment]
This issue has been solved here https://github.com/Open-EO/openeo-processes-python/pull/25
