### ISSUE TITLE
Can we set all nodata values to NaN?

### ISSUE THREAD

**Issue by sophieherrmann** [Open-EO/openeo-processes-python#35]
Currently when loading data we completely neglect the `nodata` value. Data is just loaded, independent of the used `nodata` value --- which can be quite different e,g. 0, -9999, NaN. This can lead into weird results when later applying e.g. math processes like add or multiply. Additionally the information about the `nodata` value is required to index job results into ODC, which in turn is required to realize the `load_results` process.

The information about the `nodata` value is available at least for the `xarray` - `opendatacube` implementation. OpenDataCube provides it as an attribute for each measurement. See example below and PR #35.

```
Coordinates:
  * time         (time) datetime64[ns] 2016-01-13T12:00:00 ... 2016-04-22T12:...
  * y            (y) float64 1.478e+06
  * x            (x) float64 4.883e+06
    spatial_ref  int32 0
Attributes:
    units:                fraction
    nodata:               0
    spectral_definition:  {'wavelength': [0.694, 0.713]}
    crs:                  PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984...
    grid_mapping:         spatial_ref
```

I propose that we use this information and set the `nodata` value automatically to `NaN` when loading data. Then we can assure that `nodata` is always mapped as `NaN` and we later do not have to care about it.

If `NaN` does not work for some reason, we can also agree on another **common** nodata value.

**Comment by sophieherrmann** [comment]
This would probably affect the implementation of the `fit_curve` and `predict_curve` process as it currently expects nodata value to be `0` https://github.com/Open-EO/openeo-processes-python/pull/34

**Comment by ValentinaHutter** [comment]
There are several processes that expect the `nodata` values to be NaNs. For example in the `first` process, that has been implemented before: 

https://github.com/Open-EO/openeo-processes-python/blob/master/src/openeo_processes/arrays.py#L881

Therefore it would be a good and easy solution to set the `nodata` values to NaN. 
The implementations of `fit_curve` and `predict_curve` should not be affected by that, as they accept both 0s and NaNs as `nodata` values.

**Comment by sophieherrmann** [comment]
It was decided that this is possible - implemented in https://github.com/Open-EO/openeo-processes-python/pull/36
