### ISSUE TITLE
Processes sort and order only working for "small extents"

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-processes-python#52]
As we are using Dask, the processes that are applied to a dataset are not allow to load any values of the datasets. 
The only two processes that still load data are the sort and the order processes, so when a large dataset is selected and these processes are applied, to many values will be loaded and the memory usage will be too high. 
These processes need to be updated without loading any values.

**Comment by sophieherrmann** [comment]
This was fixed with https://github.com/Open-EO/openeo-processes-python/pull/54
