### ISSUE TITLE
Implement load_results with parameters

### ISSUE THREAD

**Issue by sophieherrmann** [Open-EO/openeo-processes-python#61]
As proposed here https://github.com/Open-EO/openeo-processes/pull/292/files `load_result` will need to support filtering by bands, spatial and temporal extent. This should be implemented.

The implementation should be easy as we are getting job results from ODC.

**Comment by clausmichele** [comment]
Yes, since you are creating a new "collection" with the result, it would be possible to use the same flow as load_collection.

**Comment by ValentinaHutter** [comment]
A first implementation is available on our dev. The python client does not allow additional parameters like `bands`, `spatial_extent`, `temporal_extent` to the `load_result` process yet, they will be allowed within the next update. Once this update is released, I will continue testing.

**Comment by ValentinaHutter** [comment]
The load_result process has been tested successfully on the dev backend with all combinations of parameters (and without any parameters), so it will be added to the prod within the next update.

**Comment by ValentinaHutter** [comment]
The load_result process is now also updated on the production EODC backend.
