### ISSUE TITLE
Implement filter_bbox

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-python#72]
filter_bbox would be nice to have if we need to split a job over a large area client side (for example for UC6).
filter_bbox has the advantage that it accepts coordinates in different projections other than WGS84 / EPSG:4326 (lat/lon) and it would be required to filter a specific area (with known number of pixels) in Equi7 and merge it back client side.
This is the first implementation I have at Eurac: https://github.com/SARScripts/openeo_odc_driver/blob/master/openeo_odc_driver.py#L748

In the code I suppose that the specified projection in filter_bbox is the same the data has. There must be a check if they are really the same before proceeding.

**Comment by clausmichele** [comment]
Having the possibility to use projected coordinates in load_collection would also be nice. As I specify [here ](https://github.com/openEOPlatform/architecture-docs/issues/79#issuecomment-948564279)it's faster than using filter_bbox.

**Comment by ValentinaHutter** [comment]
I am working on the filter_bbox process and had a look at the implementation, it will be on the EODC dev soon. 
Thanks for providing your implementation, it was really helpful, the only thing I am not sure about is the connection between south/north and the x-axis and east/west and the y-axis. Do you want to connect the x-axis to south/north? :)

**Comment by clausmichele** [comment]
Yes probably I have inverted them, thanks for pointing that out. Once you will be done with this, you could also have a look at including the projected coordinates selection also in load_collection, which is more efficient.

**Comment by clausmichele** [comment]
Hi @ValentinaHutter, I think that you have missed "north" and "south" here https://github.com/Open-EO/openeo-processes-python/blob/cdb0dfce5d11a5d14a96e22c77e4a305c2541d68/src/openeo_processes/cubes.py#L1506

**Comment by ValentinaHutter** [comment]
> Hi @ValentinaHutter, I think that you have missed "north" and "south" here
> 
> https://github.com/Open-EO/openeo-processes-python/blob/cdb0dfce5d11a5d14a96e22c77e4a305c2541d68/src/openeo_processes/cubes.py#L1506

Thanks, I will immediately change it.

**Comment by ValentinaHutter** [comment]
The filter_bbox process is now on the EODC backend (development and production). 

As you can see in the load_collection implementation here: https://github.com/Open-EO/openeo-processes-python/blob/master/src/openeo_processes/cubes.py#L75 the load_collection already accepts `crs` as an input parameter, which is then given to the `odc_cube.load` function (https://github.com/Open-EO/openeo-processes-python/blob/master/src/openeo_processes/cubes.py#L27), so from the definition of the `Datacube.load` function https://datacube-core.readthedocs.io/en/datacube-1.2.2/dev/generate/datacube.Datacube.load.html I would assume, that it should already be possible, to query spatial extents with different `crs`. I have been trying it out with some `crs` options now, but could not really find a good example where it would work. I will continue testing it.
