### ISSUE TITLE
`odc` dependency?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes-python#91]
I'm trying to create a PR for #14  but I have troubles to set up my dev env. For example
https://github.com/Open-EO/openeo-processes-python/blob/a0cf4558115bbb5264e283d10685e659c09393f6/src/openeo_processes/cubes.py#L6
what is this `odc` package and how to install it? It's not listed in setup.cfg as far as I understand

**Comment by LukeWeidenwalker** [comment]
Hey Stefaan, I had the same problem a while ago and was able to install this with `pip install --extra-index-url="https://packages.dea.ga.gov.au" odc-algo` - hope this helps!

**Comment by clausmichele** [comment]
It is used for the `resample_cube_spatial `process, in the readme it is specified how to install it. @soxofaan ow would we have to include it in setup.cfg ?

**Comment by soxofaan** [comment]
Ah ok, I missed that part of the README

I think you can streamline it by adding `odc-algo` to https://github.com/Open-EO/openeo-processes-python/blob/a0cf4558115bbb5264e283d10685e659c09393f6/setup.cfg#L47-L53

and changing the `pip install .[xarray]`  installation instruction in the README to 

```
pip install --extra-index-url="https://packages.dea.ga.gov.au" .[xarray]
```

Then you can drop the `Please note: the xarray process resample_cube_spatial requires`
