### ISSUE TITLE
`add_dimension` does not work

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-python#98]
The `add_dimension` process gets parsed from openeo-odc in this way:

`_5_12 = oeop.add_dimension(**{'data': _3_3, 'name': 'bands', 'label': 'NDVI'})`

However, the implementation does not have keywords arguments in the function definition. https://github.com/Open-EO/openeo-processes-python/blob/a0cf4558115bbb5264e283d10685e659c09393f6/src/openeo_processes/cubes.py#L966

I'll add a PR for this.

**Comment by ValentinaHutter** [comment]
I am sorry, I only realised this a few days ago. This is just a typo, where I used `labels` instead of `label`. This will be changed in the next update.

**Comment by clausmichele** [comment]
I've created a PR for this https://github.com/Open-EO/openeo-processes-python/pull/100

**Comment by clausmichele** [comment]
PR merged
